/**
 * The schema-v6 token stream, rebuilt in the browser.
 *
 * This is a port of `plump/seq/tokens.py` from the training project, and it has
 * to stay one: the model only plays well on the exact stream it was trained on,
 * and a mismatch produces no error, just a worse opponent. `npm run check` runs
 * `scripts/check-plump-tokens.mjs`, which replays fixtures generated by the
 * Python builder and asserts every row here matches it exactly.
 *
 * It lives apart from model-client.js so Node can import it without pulling in
 * onnxruntime-web from a CDN.
 */

const TOKEN = Object.freeze({
  GAME: 1,
  HAND: 2,
  BID: 3,
  PLAY: 4,
  TRICK_WIN: 5,
  TURN: 6,
});

const NEXT = Object.freeze({ NONE: 0, BID: 1, PLAY: 2 });

export const SUITS = ["spades", "hearts", "diamonds", "clubs"];

// Slot layout. The first twelve are the original schema-v6 fields; slots 12-15
// carry the causal bidding state; 16-24 hold a TRICK_WIN row's remaining hand;
// slot 25 is the compact id for which base fields are absent.
const SLOT = Object.freeze({
  TYPE: 0,
  REL_PLAYER: 1,
  RANK: 2,
  SUIT: 3,
  CARD: 4,
  BID: 5,
  TRICK: 6,
  POS_IN_TRICK: 7,
  HAND_SIZE: 8,
  NUM_PLAYERS: 9,
  NEXT_ACTOR: 10,
  NEXT_PHASE: 11,
  BIDS_MADE: 12,
  BID_SUM: 13,
  BID_PRESSURE: 14,
  BIDS_REMAINING: 15,
  REMAINING_HAND_START: 16,
  NA_PATTERN: 25,
});

const BASE_TOKEN_WIDTH = 16;
export const WIDTH = 26;

// The deployed vocabulary limits, i.e. SeqModelConfig(max_players=5,
// max_hand_size=10). model-client.js checks a loaded manifest against these.
export const MODEL_LIMITS = Object.freeze({
  max_players: 5,
  max_hand_size: 10,
  trick_win_token: true,
  turn_token: "bid",
});

const MAX_PLAYERS = MODEL_LIMITS.max_players;
const MAX_HAND_SIZE = MODEL_LIMITS.max_hand_size;
const NUM_CARDS = 52;

const NA = Object.freeze({
  PLAYER: MAX_PLAYERS,
  RANK: 13,
  SUIT: 4,
  CARD: NUM_CARDS,
  BID: MAX_HAND_SIZE + 1,
  TRICK: MAX_HAND_SIZE,
  POS: MAX_PLAYERS,
  BIDS_MADE: MAX_PLAYERS + 1,
  BID_SUM: MAX_PLAYERS * MAX_HAND_SIZE + 1,
  BID_PRESSURE: MAX_PLAYERS * MAX_HAND_SIZE + 1,
  BIDS_REMAINING: MAX_PLAYERS + 1,
});

// Bid pressure is (hand size - bids so far), which goes negative, so it is
// stored shifted into a non-negative vocabulary.
const BID_PRESSURE_OFFSET = (MAX_PLAYERS - 1) * MAX_HAND_SIZE;

// Sentinel per base slot; null means the field is always present.
const BASE_SLOT_NA_IDS = [
  null,
  NA.PLAYER,
  NA.RANK,
  NA.SUIT,
  NA.CARD,
  NA.BID,
  NA.TRICK,
  NA.POS,
  null,
  null,
  NA.PLAYER,
  NEXT.NONE,
  NA.BIDS_MADE,
  NA.BID_SUM,
  NA.BID_PRESSURE,
  NA.BIDS_REMAINING,
];

// Every absence mask schema-v6 can emit. Index 0 is reserved for padding rows
// and contributes exactly zero; real rows use one of the rest. A mask outside
// this table means the row was built wrong, so the lookup throws.
const NA_PATTERN_MASKS = [
  0, 0x00dc, 0x00e0, 0x00fc, 0x0c7e, 0x0cdc, 0x0ce0, 0xf020, 0xf03c, 0xf0bc,
  0xfc20, 0xfcbc,
];

const relative = (player, observer, players) =>
  (player - observer + players) % players;

const cardId = (card) => SUITS.indexOf(card.suit) * 13 + (card.rank - 2);

const baseToken = (players, handSize) => [
  0, NA.PLAYER, NA.RANK, NA.SUIT, NA.CARD, NA.BID, NA.TRICK, NA.POS,
  handSize, players, NA.PLAYER, NEXT.NONE,
  NA.BIDS_MADE, NA.BID_SUM, NA.BID_PRESSURE, NA.BIDS_REMAINING,
  NA.CARD, NA.CARD, NA.CARD, NA.CARD, NA.CARD, NA.CARD, NA.CARD, NA.CARD,
  NA.CARD,
  0,
];

/** Attach the causal aggregate bidding state to a row that carries it. */
const setBidPressure = (token, players, handSize, bidsMade, bidSum) => {
  token[SLOT.BIDS_MADE] = bidsMade;
  token[SLOT.BID_SUM] = bidSum;
  token[SLOT.BID_PRESSURE] = handSize - bidSum + BID_PRESSURE_OFFSET;
  token[SLOT.BIDS_REMAINING] = players - bidsMade;
};

/** Encode which base fields are absent. Must run after every other mutation. */
const setNaPattern = (token) => {
  let mask = 0;
  for (let slot = 0; slot < BASE_TOKEN_WIDTH; slot += 1) {
    const sentinel = BASE_SLOT_NA_IDS[slot];
    if (sentinel !== null && token[slot] === sentinel) mask |= 1 << slot;
  }
  const pattern = NA_PATTERN_MASKS.indexOf(mask);
  if (pattern < 0) {
    throw new Error(
      `Unsupported token NA pattern 0x${mask.toString(16).padStart(4, "0")}.`,
    );
  }
  token[SLOT.NA_PATTERN] = pattern;
};

const turnToken = (
  players,
  handSize,
  actor,
  phase,
  { trick = null, position = null, bidsMade = null, bidSum = null } = {},
) => {
  const token = baseToken(players, handSize);
  token[SLOT.TYPE] = TOKEN.TURN;
  token[SLOT.REL_PLAYER] = actor;
  if (trick !== null) token[SLOT.TRICK] = trick;
  if (position !== null) token[SLOT.POS_IN_TRICK] = position;
  token[SLOT.NEXT_ACTOR] = actor;
  token[SLOT.NEXT_PHASE] = phase;
  if (phase === NEXT.BID) {
    setBidPressure(token, players, handSize, bidsMade, bidSum);
  }
  return token;
};

const eventToken = (
  event,
  observer,
  players,
  handSize,
  remainingHand,
  bidsMade,
  bidSum,
) => {
  const token = baseToken(players, handSize);
  token[SLOT.REL_PLAYER] = relative(event.player, observer, players);

  if (event.type === "bid") {
    token[SLOT.TYPE] = TOKEN.BID;
    token[SLOT.BID] = event.bid;
    // A BID row carries the state *after* its own bid.
    setBidPressure(token, players, handSize, bidsMade, bidSum);
  } else if (event.type === "play") {
    token[SLOT.TYPE] = TOKEN.PLAY;
    token[SLOT.RANK] = event.card.rank - 2;
    token[SLOT.SUIT] = SUITS.indexOf(event.card.suit);
    token[SLOT.CARD] = cardId(event.card);
    token[SLOT.TRICK] = event.trickIndex;
    token[SLOT.POS_IN_TRICK] = event.position;
  } else if (event.type === "trick_win") {
    token[SLOT.TYPE] = TOKEN.TRICK_WIN;
    token[SLOT.TRICK] = event.trickIndex;
    const values = remainingHand.map(cardId).sort((a, b) => a - b);
    for (let index = 0; index < values.length; index += 1) {
      token[SLOT.REMAINING_HAND_START + index] = values[index];
    }
  }
  return token;
};

/** Build the exact schema-v6 actor stream used by the training project. */
export function buildTokens(game, observer) {
  const round = game.round;
  const players = game.numPlayers;
  const handSize = round.handSize;
  const biddingPosition = relative(observer, round.biddingStart, players);
  const initialHand = [...round.initialHands[observer]].sort(
    (a, b) => cardId(a) - cardId(b),
  );

  const gameRow = baseToken(players, handSize);
  gameRow[SLOT.TYPE] = TOKEN.GAME;
  gameRow[SLOT.POS_IN_TRICK] = biddingPosition;
  const tokens = [gameRow];

  for (const card of initialHand) {
    const token = baseToken(players, handSize);
    token[SLOT.TYPE] = TOKEN.HAND;
    token[SLOT.REL_PLAYER] = 0;
    token[SLOT.RANK] = card.rank - 2;
    token[SLOT.SUIT] = SUITS.indexOf(card.suit);
    token[SLOT.CARD] = cardId(card);
    tokens.push(token);
  }
  // No bid has been made when the prefix is written.
  for (const token of tokens) setBidPressure(token, players, handSize, 0, 0);

  const firstActor = relative(round.biddingStart, observer, players);
  // This model was trained with turn_token="bid".
  tokens.push(
    turnToken(players, handSize, firstActor, NEXT.BID, {
      bidsMade: 0,
      bidSum: 0,
    }),
  );

  const remaining = new Map(initialHand.map((card) => [cardId(card), card]));
  const remainingAtWin = new Map();
  round.events.forEach((event, index) => {
    if (event.type === "play" && event.player === observer) {
      remaining.delete(cardId(event.card));
    } else if (event.type === "trick_win") {
      remainingAtWin.set(index, [...remaining.values()]);
    }
  });

  let bidsMade = 0;
  let bidSum = 0;
  round.events.forEach((event, index) => {
    if (index > 0 && event.type === "bid") {
      // A TURN row carries the state *before* the bid it announces.
      tokens.push(
        turnToken(
          players,
          handSize,
          relative(event.player, observer, players),
          NEXT.BID,
          { bidsMade, bidSum },
        ),
      );
    }
    if (event.type === "bid") {
      bidsMade += 1;
      bidSum += event.bid;
    }
    tokens.push(
      eventToken(
        event,
        observer,
        players,
        handSize,
        remainingAtWin.get(index) || [],
        bidsMade,
        bidSum,
      ),
    );
  });

  // Each row announces an immediately following public action.
  for (
    let position = Math.max(0, 1 + handSize);
    position < tokens.length - 1;
    position += 1
  ) {
    const upcoming = tokens[position + 1];
    if (upcoming[SLOT.TYPE] === TOKEN.BID || upcoming[SLOT.TYPE] === TOKEN.PLAY) {
      tokens[position][SLOT.NEXT_ACTOR] = upcoming[SLOT.REL_PLAYER];
      tokens[position][SLOT.NEXT_PHASE] =
        upcoming[SLOT.TYPE] === TOKEN.BID ? NEXT.BID : NEXT.PLAY;
    } else if (upcoming[SLOT.TYPE] !== TOKEN.TURN) {
      tokens[position][SLOT.NEXT_ACTOR] = NA.PLAYER;
      tokens[position][SLOT.NEXT_PHASE] = NEXT.NONE;
    }
  }

  if (
    round.currentPlayer !== null &&
    ["bidding", "playing"].includes(round.phase)
  ) {
    const actor = relative(round.currentPlayer, observer, players);
    if (round.phase === "bidding") {
      // Kept byte-for-byte compatible with the training policy builder,
      // including its explicit pending-decision register.
      tokens.push(
        turnToken(players, handSize, actor, NEXT.BID, { bidsMade, bidSum }),
      );
    } else {
      tokens.at(-1)[SLOT.NEXT_ACTOR] = actor;
      tokens.at(-1)[SLOT.NEXT_PHASE] = NEXT.PLAY;
      // PLAY has no separate TURN token in this checkpoint.
    }
  }

  for (const token of tokens) setNaPattern(token);
  return tokens;
}

/** Build the perfect-information, absolute-seat stream used by the PPO oracle. */
export function buildOracleTokens(game) {
  const round = game.round;
  const handSize = round.handSize;
  const actorTokens = buildTokens(game, 0);
  const oracleHands = round.initialHands.flatMap((hand, owner) =>
    [...hand]
      .sort((a, b) => cardId(a) - cardId(b))
      .map((card) => {
        const token = baseToken(game.numPlayers, handSize);
        token[SLOT.TYPE] = TOKEN.HAND;
        token[SLOT.REL_PLAYER] = owner;
        token[SLOT.RANK] = card.rank - 2;
        token[SLOT.SUIT] = SUITS.indexOf(card.suit);
        token[SLOT.CARD] = cardId(card);
        setBidPressure(token, game.numPlayers, handSize, 0, 0);
        return token;
      }),
  );
  const tokens = [
    actorTokens[0],
    ...oracleHands,
    ...actorTokens.slice(1 + handSize),
  ];
  // Remaining-hand snapshots belong only to an observer stream. The oracle
  // derives every current hand from its full-deal prefix and public plays.
  for (const token of tokens) {
    token.fill(NA.CARD, SLOT.REMAINING_HAND_START, SLOT.NA_PATTERN);
    setNaPattern(token);
  }
  return tokens;
}

export const modelCardId = cardId;
