#!/usr/bin/env python3
"""Export the training curves shown under "How the agent was trained".

Reads the distillation run, the RL6 PPO run, and the RL6 lineage round robin
from a plump-bot checkout and writes a small ES module of smoothed series.
Standard library only, so it runs without the training environment.
"""

from __future__ import annotations

import argparse
import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_PLUMP_BOT = ROOT.parent / "plump-bot"
OUTPUT = ROOT / "RL-environment" / "plump" / "training-data.js"


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="") as handle:
        return list(csv.DictReader(handle))


def smoothed(
    rows: list[dict[str, str]],
    column: str,
    *,
    window: int,
    stride: int,
    start: int | None = None,
    end: int | None = None,
) -> list[list[float]]:
    """Centered moving average, sampled every ``stride`` iterations.

    Rows with an empty value are skipped rather than read as zero. Near the
    edges the window shrinks to what exists, so the first and last points are
    still averages of real updates.
    """
    points = [
        (int(row["iteration"]), float(row[column]))
        for row in rows
        if row.get(column) not in (None, "")
        and (start is None or int(row["iteration"]) > start)
        and (end is None or int(row["iteration"]) <= end)
    ]
    series: list[list[float]] = []
    half = window // 2
    for index in range(0, len(points), stride):
        lo, hi = max(0, index - half), min(len(points), index + half + 1)
        values = [value for _, value in points[lo:hi]]
        series.append([points[index][0], round(sum(values) / len(values), 4)])
    if series[-1][0] != points[-1][0]:
        lo = max(0, len(points) - 1 - half)
        values = [value for _, value in points[lo:]]
        series.append([points[-1][0], round(sum(values) / len(values), 4)])
    return series


def round_robin(path: Path) -> list[dict[str, float]]:
    return [
        {
            "iteration": int(row["iteration"]),
            "run": row["run"],
            "reward": round(float(row["relative_reward"]), 4),
            "low": round(float(row["relative_reward_ci_low"]), 4),
            "high": round(float(row["relative_reward_ci_high"]), 4),
            "rounds": int(row["rounds"]),
        }
        for row in read_rows(path)
    ]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--plump-bot", type=Path, default=DEFAULT_PLUMP_BOT)
    parser.add_argument(
        "--tournament",
        default="rr-5600-to-27700-stride1000.csv",
        help="Round-robin CSV under runs/rl-v6/tournaments/.",
    )
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args()

    runs = args.plump_bot / "runs"
    distill = read_rows(runs / "distill-v5" / "metrics.csv")
    rl6 = read_rows(runs / "rl-v6" / "metrics.csv")
    # RL6 forked from the distilled student at update 5600; its metrics file
    # starts there too, but be explicit so a re-fork cannot leak old rows.
    rl6_start = 5600

    data = {
        "source": {
            "distillRun": "distill-v5",
            "rlRun": "rl-v6",
            "tournament": args.tournament,
        },
        "distillKl": smoothed(
            distill, "distill_kl", window=60, stride=25, end=rl6_start
        ),
        "oracleValueRmse": smoothed(
            rl6, "critic_all_player_rmse", window=200, stride=100, start=rl6_start
        ),
        "actorValueRmse": smoothed(
            rl6, "actor_all_player_rmse", window=200, stride=100, start=rl6_start
        ),
        "suitLoss": smoothed(rl6, "loss_suit", window=400, stride=100, start=rl6_start),
        "rankBoundaryLoss": smoothed(
            rl6, "loss_rank_boundary", window=400, stride=100, start=rl6_start
        ),
        "roundRobin": round_robin(runs / "rl-v6" / "tournaments" / args.tournament),
    }

    body = json.dumps(data, separators=(",", ":"))
    args.output.write_text(
        "// Generated by scripts/export-plump-training-data.py; do not edit by hand.\n"
        f"export const PLUMP_TRAINING_DATA = {body};\n"
    )
    print(f"wrote {args.output} ({args.output.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
